version: '3.9'

services:
  # server:
  #   build:
  #     context: .
  #     target: final
  #   container_name: sso
  #   ports:
  #     - 6003:6003
  #   volumes:
  #     - ./config:/config
  #   environment:
  #     - CONFIG_PATH=/config/local.yaml

  #   depends_on:
  #     postgres_sso:
  #       condition: service_healthy
  #     redis_sso:
  #       condition: service_healthy
  
  postgres_sso:
    image: postgres:latest
    container_name: postgres_sso
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "auth"
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 30s
      timeout: 10s
      retries: 5
    
  redis_sso:
    image: redis:latest
    container_name: redis_sso
    restart: always
    environment:
      REDIS_PASSWORD: "1234"
      REDIS_PORT: 6379
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
  
  prometheus:
    container_name: prometheus_container
    image: prom/prometheus
    volumes:
      - ./docker/monitoring/prometheus-local.yml:/etc/prometheus/prometheus.yml:Z
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=20d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - '9090:9090'
  
  grafana:
    container_name: grafana_container
    image: grafana/grafana
    ports:
      - '3000:3000'
