env: "local"
keys_update_interval: 24h

access_token_ttl: 15m
refresh_token_ttl: 43200m #30 days
code_ttl: 10m
token_ttl: 1h

grpc:
  host: "0.0.0.0"
  port: 6003

psql:
  host: "localhost"
  port: 5432
  user: "root"
  password: "1234"
  db: "auth"

redis:
  host: "localhost"
  port: 6379
  password: "1234"

observability:
  traces:
    endpoint: "localhost:4317"
    service_name: "apphelper-sso"
    service_version: "1.0.0"
  metrics:
    port: 6004

redpanda:
  brokers:
    - "localhost:9092"
  group_id: "apphelper-sso"
  topics:
    - "sso.auth.registered"
    - "sso.auth.password.changed"
    - "sso.auth.code.updated"