env: "local"
keys_update_interval: 24h

grpc:
  host: "localhost"
  port: 6003
  access_token_ttl: 60m
  refresh_token_ttl: 43200m #30 days

psql:
  host: "localhost"
  port: 5432
  user: "root"
  password: "1234"
  db: "auth"

redis:
  host: "localhost"
  port: 6379
  password: "1234"