env: "local"
keys_update_interval: 24h

grpc:
  host: "0.0.0.0"
  port: 6003
  access_token_ttl: 15m
  refresh_token_ttl: 43200m #30 days

psql:
  host: "localhost"
  port: 5432
  user: "root"
  password: "1234"
  db: "auth"

redis:
  host: "localhost"
  port: 6379
  password: "1234"

report_client:
  addr: "localhost:49102"

schedule_client:
  addr: "localhost:49104"